### ISSUE TITLE
broken summary window

### ISSUE THREAD

**Issue by iron217** [Dkhub85/COTG-Dfunky#11]
<img width="1034" alt="2019-01-03 21 54 44" src="https://user-images.githubusercontent.com/46353863/50655890-8c088d00-0fa2-11e9-80eb-b100808eede0.png">

google chrome 71.0.3578.98 
13.3 inches display
screen resolution 2560×1600

**Comment by iron217** [comment]
<img width="892" alt="2019-01-03 22 07 31" src="https://user-images.githubusercontent.com/46353863/50656383-130a3500-0fa4-11e9-9e19-4b39e09f19d7.png">

broken tabs troops and resources, other tabs work fine

**Comment by rbraband** [comment]
Hi, you mean the faulty layout if the height of the layer is not sufficient?
Can you confirm that if you enlarge the layer, with the small handle at the right-bottom, the layout will be fine?

**Comment by iron217** [comment]
I also installed cfunky and it looks fine there
<img width="913" alt="2019-01-05 12 06 33" src="https://user-images.githubusercontent.com/46353863/50722599-769a7c80-10e2-11e9-99c7-4979c844c640.png">

**Comment by Dkhub85** [comment]
fixed
